canonical/ubuntu-maintainers-handbook

BugReportResponses.md
CommittingChanges.md
Concepts.md
MergeProposal.md
PackageBuilding.md
PackageFixing.md
README.md
Setup.md
Unsorted.md

This rolls up a bunch of improvements to the handbook:
* Fixes to grammatical errors
* Expansion of Concepts page with discussion of basics
* Additional tips for setup
* Detailed discussion for SRU processes

Elaborate concepts and procedures

---

BugReportResponses.md
BugTriage.md
CommittingChanges.md
Concepts.md
DebianPatch.md
MergeProposal.md
PackageFixing.md
PackageMerging.md
PackageTests.md
README.md
Unsorted.md

(Also, standardize on US English spellings for consistency.)

Spelling fixes

---

PackageTests.md

I did intentionally not go deeper as that would then be for the man-ages or the linked wiki entries.
But to list them as options is IMHO helpful to new team members.

Extend autopkgtest hints

---

BugTriage.md

After helping @utkarsh2102 today to get him inserted I thought it would be useful to document this a bit better (than not at all).

document how we assign triage tasks

---

CommittingChanges.md

Hi,
these are minor changes, but I'm putting them here just for your information in the sense that you might be interested in making them.
Thanks!

Adjusting path for well known archives

---

Concepts.md

This continues #24 with the necessary fix-ups and links.

Ubuntu policy updates

---

ProposedMigration.md
Unsorted.md

Updated due to:
https://lists.ubuntu.com/archives/ubuntu-devel/2021-November/041663.html

Migration: mention the new migration-reference/0

---

PackageMerging.md

Hi team,
for documenting the empty dirs issue that we may face when doing a merge, I've introduced a new section on Package Merging where we can collect non-normal situations. Thanks to @bryceharrington for the idea and the material.
I included entirely the text from Robie's script because, for me, it explains why the issue arises (why is a problem that we get empty dirs?), but if you consider it is too large I can think it over.
Thanks in advance.

Adding Known Issues section and  Empty dirs issue on Package Merging.

---

PackageMerging.md

Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>

Document missing dpkg-buildpackage option

---

PackageMerging.md

Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>

Describe process to add new changes during a merge

---

PackageMerging.md

These are just minor improvements to the docs. See the commit messages for further reference on each specific change.

Minor package merging documentation improvements

---

ProposedMigration.md
README.md

Expands the proposed migration documentation to include discussion of a
variety of issues that can come up, and techniques for resolving them.
Notably, this further fills in the glossary of terminologies shown on
the Update Excuses page, listed in a way that should be searchable
in-doc as well as linkable via html anchors.  For example, to understand
what "Implicit dependency ..." means, one could do a text search on the
file from the web browser, or direct link to the relevant section via
url like:
http://umh.com/ProposedMigration.html#implicit-dependency-aaa-bbb
The top level README is also updated with direct links to this and other
pages.

ProposedMigration: Explain excuses and suggest course of actions

---

ProposedMigration.md

As shown in standup yesterday, probably worth to mention in UMH.

ProposedMigration.md: mention update_output

---

Concepts.md

New information with descriptions of the fields from the d/control file has been added to the Concepts.md. That information is compressed and helps to gain basic knowledge of the debian/control.

Add information about the control file to Concepts.md

---

CommittingChanges.md

This is my understanding of the versioning scheme. Please reject if this is incorrect.

CommittingChanges: Reword Security update -> Recommended version

---

CommittingChanges.md
Concepts.md
DebianPatch.md
PackageBuilding.md
PackageTests.md
Setup.md

I have some questions, added to the PR inline
In the interests of not making the PR too large I'm
submitting the first few pages. Concepts.md needs a
bigger overhaul for the flow/organisation so I've 
focused on the spelling/grammar for now.

Polishing changes

---

Transitions.md

Spelling/grammar/clarity edits

Polishing edits on Transitions.md

---

MainInclusion.md

Spelling/grammar/clarity edits

Polishing edits on MainInclusion.md

---

BugReportResponses.md
DocTriage.md

Questions I had on the content are added as review comments.
Mostly just minor polishing.

Polishing changes part 4

---

SalsaDualMaintenance.md

Spelling/grammar, consistency in style edits

Polishing edits on SalsaDualMaintenance.md

---

MembershipInMOTU.md

Polishing edits on MOTU page

---

MembershipInCoreDev.md

Polishing edits on Core Dev page

---

MembershipInPackageSet.md

Polishing edits on Package Set page

---

ProposedMigration.md

Spelling/grammar/clarity/style

Polishing edits on ProposedMigration

---

PackageMerging.md

Spelling/grammar/clarity edits

Polishing edits on PackageMerging.md

---

MergeProposal.md
PackageFixing.md
PackageTests.md
Sponsorship.md
Syncs.md

As before, questions added to the PR inline

Polishing changes pt 2

---

BugFixingCheckList.md
CheckListsSheets.md

Polish edits on checklist section

---

PackageTests.md

Fix indentation in code blocks

---

README.md

Polish edits on Index page

---

BugTriage.md
DebugApportCrash.md
MergeProposalReview.md

Questions I had on the content are added inline as review comments.

Polishing changes part 3

---

PackageMerging.md

- Rebuild package with itself if the package is using bootstrap to avoid difficult situation where you will have to ask for help.

Add smoke tests suggestion

---

PackageMerging.md
Setup.md

updating the make a bug report section. picking instructions from https://wiki.ubuntu.com/UbuntuDevelopment/Merging

Updating Merging instructions

---

PackageMerging.md

use git diff --stat to see diff stat

use git diff --stat to see diff stat

---

PackageMerging.md
Sponsorship.md

Along reviewing and sponsoring MRs I've came by a few weakly defined areas which I wanted to improve. In particular sponsoring and -v on merge uploads.

Improve sponsoring and merge changes

---

CommittingChanges.md

Add information about --CL-- and UD-Forwarded

---

BugFixingCheckList.md
BugReportResponses.md
PackageFixing.md
ProposedMigration.md
Reference/PathToUploadRights.md
VersionStrings.md

* "situationis" -> "situations"
* Adopt links to new SRU documentation: https://canonical-sru-docs.readthedocs-hosted.com/

Update SRU links, fix typos

---

Setup.md

Remove piuparts from package install list - not needed and missing in noble

---

DebianPatch.md
PackageBuilding.md

While looking into what we discussed I found even more.
Overall this PR should help to lay down more "things we usually do" into the written UMH.

Standup discussion follow up

---

MergeProposal.md
MergeProposalReview.md

As a follow up to realize we didn't catch the libvirt component mismatch I wanted to extend the review guidance.
And when touching it I found more and more that wasn't there yet so I kept (hopefully) improving it.

Enhance patch review

---

Concepts.md
PackageBuilding.md

I was following the UMH to get the lay of the land, and found those small caveats and inconsistencies.

Tweaks and small improvements to the handbook

---

VersionStrings.md

Discussed at [1] and after general consensus turned into this commit.
[1]: https://lists.ubuntu.com/archives/ubuntu-devel/2025-April/043323.html

versions: policy for native Ubuntu packages

---

PackageFixing.md
Setup.md

since LXD can do VMs, let's use that for a more streamlined experience :)

replace uvt VM creation with lxd VMs
