canonical/ubuntu-maintainers-handbook

PackageBuilding.md
Setup.md

This series of commits aim at improving the current PackageBuilding page.  These are the additions I've made:
* New section **Downloading the orig tarball (optional)**
* Improve on section **Building Source Packages** (by mentioning that it's possible to invoke `dpkg-buildpackage` locally as well).
* New section **Using sbuild**, which also mentions how to workaround a Launchpad PPA bug.
Finally, I also mention the possibility of setting the `DEBSIGN_*` variables on `.profile`.

Improve PackageBuilding

---

Concepts.md
MembershipInPackageSet.md
PackageBuilding.md
PackageTests.md
README.md
Setup.md

First cut at a page explaining packageset membership.
Yes, there is already official documentation in the main wiki but this combines that with advice from https://wiki.ubuntu.com/RobieBasak/DMB/CoreDev and presents the information in more of a concise worksheet geared to server team members.
The other commit updates some of the examples from bionic to focal, where it could be done with no impact to the example (i.e. by making version numbers inaccurate).

Packageset membership

---

PackageMerging.md

It doesn't make sense to remake the "logical" tag
when a conflict occurs. That should happen after
tagging the "logical" tag and not before.
Signed-off-by: Utkarsh Gupta <<utkarsh.gupta@canonical.com>>

Don't remake the logical tag if a conflict occurs

---

ProposedMigration.md
Unsorted.md

First cut at some initial docs about proposed migration.
The ubuntu wiki has a more authoritative guide, but is structured more as a reference.  This is intending to serve more as a tutorial and a collection point to links to the various sources of information a new +1 maintainer would need.
This still lacks a bit of polish (the glossary section in particular is going to render weirdly), but I think it's ready for an initial review.

Proposed migration

---

Setup.md

I'm guessing this is a typo, as a cursory search didn't turn up any "Dropbox" container runtime.

Docker is a container runtime, not Dropbox

---

PackageTests.md

It was quite hard to read without the block quotes.

PackageTests: fix formatting for image list command

---

PackageTests.md

In the past, I've used ubuntu-daily:focal but I've been hitting
lots of weird issues. The squad then suggested using images:ubuntu/focal
instead and those images have been working flawlessly.
Very recently, our new starter, Miriam, hit the same issue where
the former image didn't really work and the latter did. There
are more issues with the former one so suggesting the latter one FTW.
And whilst at it, also switch to devel release, that is, from Focal
to Impish.

Switch image from ubuntu-daily:$release to images:ubuntu/$release

---

MergeProposal.md
PackageBuilding.md
PackageFixing.md
PackageMerging.md

With #20 being merged in, this does the follow-up fixes of
more mentions of the ubuntu-daily images.
I've intentionally let "cosmic" and "bionic" remain there
and did not convert them to more recent releases because
I believe that'd be a separate thing from this.
I'll do the switch from mentions of older releases to the newer
ones soon, too. But it isn't a blocker, really.

Drop ubuntu-daily:$release in favor of images:ubuntu/$release

---

PackageBuilding.md

Hi team,
I found a reference to the former option --sign of git-ubuntu (I suppose is from git ubuntu build-source that is no longer available).
I made a few changes that reflect that and also a fix for using the command as copy-paste directly.
Thanks!

PackageBuilding.md: Removing reference to git ubuntu --sign

---

PackageFixing.md

Replace [Regression Potential] with [Where problems could occur] to be consistent with the official SRU Bug Template [1].
[1] https://wiki.ubuntu.com/StableReleaseUpdates#SRU_Bug_Template

Update the SRU template sections

---

PackageMerging.md
Syncs.md

Hi team,
as a result of the freeipmi merge that resulted in a sync task, I wrote a little about that. Christian gave me several pages about Syncs in the Ubuntu wiki that I tried to summarize, but I focused on the case that we're doing a merge task and we discovered we have not Ubuntu delta, so I don't enter in detail about the other cases because I don't face them yet (but I did this like a new page for this reason, in the sense we wanted to do it in the future).
I would have liked to talk a little more about the message "Source package <whatever> is temporarily blacklisted (blacklisted_current).", to see how to track these special cases ... so suggestions are more than welcome.
Anything you consider needs a change, feel free to let me know about it (suggestions also, of course!).
Thanks …

New entry on Package Merging: Syncs

---

PackageTests.md

Triggered by +1 maintenance by Paride, I hope this helps to recreate such cases.

PackageTests.md: explain how to restrict networking

---

ProposedMigration.md

As it recently came up in the team drop one more info-snippet that can be find via search-engine or by grepping/reading the maintainers handbook.

ProposedMigration.md: Mention auto-include triggering component mismatches

---

DebugApportCrash.md
PackageFixing.md
PackageTests.md
ProposedMigration.md
README.md

I've not tested that this renders correctly, but this is a first draft of documentation on how to extract usable stack traces from user-supplied <whatever>.crash files.
A couple spell-fixes / copyedits are also included in this PR.

Apport crash debug

---

PackageMerging.md

When manually pulling the sources for a new merge, one should also get
the gpg signature file, if available. This patch changes the line
suggesting the mv command after the Debian sources are fetched to
suggest that such file should also be moved over.
Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>

Document fetching detached gpg signature file

---

BugTriage.md

Hi,
while trying to do the simple change of adding the mysql triage steps to the handbook as [suggested by bryce](https://lists.ubuntu.com/archives/ubuntu-server/2022-February/009142.html) I realized we have plenty of outdated and redundant content int he wiki. The UMH is the place we use, review and update more regularly.
This tries to update and unify things accordingly to the place we actually watch (=UMH).
After this PR is discussed and merged the actions to be taken in other places are:
- Wiki: https://wiki.ubuntu.com/ServerTeam/mysql now covered as special case
in UMH
=> remove the wiki page, replace with a forwarder to the UMH page
- Ubuntu Server Bug Triage - this is a nice general intro (not too complex) and
suggests the community to help us. I'd keep that, but mention that the …

Update Triage work and integrate most of the wiki content (reduces redundancy)

---

PackageMerging.md

This syncs the information available in [1] regarding the split tag
verification step
[1] https://wiki.ubuntu.com/UbuntuDevelopment/Merging/GitWorkflow#Detailed_workflow

Document merge split tag verification

---

.gitignore
generate-html
generate-pdf

Adds a couple pandoc scripts to generate HTML and PDF output.
The HTML uses GitHub-Formatted Markdown (gfm) style, which seems to reasonably match the generated output we have on github.
The PDF output doesn't preserve UTF-8 symbols, and doesn't linkify URLs, but is probably good enough if people want to print out the doc or whatnot.
Both these could probably be done better with a Makefile, but will leave that to future work for someone that'd prefer it.  :-)

Generate html and pdf

---

Syncs.md

To perform a sync, a requester must check if the Debian package one
wants to sync is available in launchpad. That should be done in the
Debian publishing history page in Launchpad instead of in the Ubuntu
one.
Signed-off-by: Athos Ribeiro <athos.ribeiro@canonical.com>

Fix Debian publishing history URL

---

Setup.md

This is an old reference that shall no more be used.
It also causes conflicts on some installations.

Setup: replace no more available qemu-kvm

---

BugTriage.md

We have said that we want to try the weekly housekeeping session
as well as dropping server-next tag for a while and make it part of the
documentation once we are happy with it. It seems to work fine so let us
put it into the handbook.
In addition that will help others to run the meeting as this will list
the commands to generate bug lists as well as where to find old bug
tracking lists.

BugTriage.md: update tagging and housekeeping

---

PackageBuilding.md
PackageMerging.md
PackageTests.md

We now have some command line tools to assist in creating PPAs and
running autopkgtests against them.  Include explanations using these
tools.
Don't drop the preexisting documentation doing the processes manually
since they may still be relevant for corner cases that the tools don't
cover, or other situations where a manual approach would be preferred.

Explain how to run autopkgtests on a PPA using tooling

---

PackageFixing.md

This commit fixes a relative link in the markdown file, and also adds a longer description to the relative link.

PackageFixing: update relative link

---

MergeProposal.md

Hi!
I noticed that most (if not all) of you use git ubuntu submit for this, but I'm a Miriam of the past (:$) who looks on this page to create a PM on Launchpad (merges or bug fixes, whatever)... so, for the Miriam of the future who might forget the git ubuntu tool and go back to what she learned in her origins in Server Team, I propose this change.
Thank you!

MergeProposal.md: Change the default reviewer on manual submission

---

BugFixingCheckList.md
MainInclusion.md
MergeProposal.md
ProposedMigration.md
Sponsorship.md

For manually filed reviews, `canonical-server-reporter` should be used now instead of `canonical-server` for the Server Team.
Also, generalize the instructions to direct people to file review requests with their own team, with the Canonical Server team listed only as an example.

Update reviewer teams

---

PackageTests.md

I followed this Guide and got a `ModuleNotFoundError` for `glance` when I ran the examples with the `nova` script:
```
Traceback (most recent call last):
File "<stdin>", line 2, in <module>
ModuleNotFoundError: No module named 'glanceclient'
```
`autopkgtest` has no hard dependency to `python3-glanceclient`, because the nova script assumes that it is running in an environment where it is already installed:
```bash
$ head ssh-setup/nova
#!/bin/sh
#
#
```
I think it should not be mentioned in the [Setup.md](https://github.com/canonical/ubuntu-maintainers-handbook/blob/main/Setup.md), because this dependency is only needed by people who what to use Canonistack with `autopkgtest`.

PackageTests.md: Added install glance reminder to Canonistack Section

---

Setup.md

When I created a change to a package (in my case `inetutils` and `iputils`) the `Maintainer:` field the `.changes` file was overwritten, which was not intended. 
Intended:
```
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Changed-By: Dominik Viererbe <dominik.viererbe@canonical.com>
```
Actual:
```
Maintainer: Dominik Viererbe <dominik.viererbe@canonical.com>
Changed-By: Dominik Viererbe <dominik.viererbe@canonical.com>
```
This resulted in the following `lintian` error:
```
E: iputils changes: inconsistent-maintainer Dominik Viererbe <dominik.viererbe@canonical.com> (changes vs. source) Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
N: 
N:   The Maintainer address in a group of related processables is inconsistent
N:   as indicated.
N:   
N:   This …
```

`sbuild` should not overwrite the `Maintainer:` field of `.changes` files by default

---

ProposedMigration.md

Back in "f3786c9 Migration: mention the new migration-reference/0" we added an info about what migration-reference runs are and how to use them. This was, by accident, removed in: "ac4f624 ProposedMigration: Explain excuses and suggest course of actions".
Let us add that back, in a more elaborate way, as it has become a quite common task for anyone dealing with proposed migration nowadays.

Migration: mention the new migration-reference/0

---

BugFixingCheckList.md
PackageTests.md

As requested a while back by paelzer, this updates references to lp-tests-ppa to use ppa-dev-tools.  For the most part command should be drop-in replacements but some features (like --showpass) aren't implemented yet.
There are already basic usage directions for ppa-dev-tools elsewhere in the document, so this branch does not need to explain installation or basic usage.

Replace links to lp-test-ppa with equivalent ppa-dev-tools links

---

BugTriage.md
DocTriage.md
README.md

Provide mostly platform-independent instructions for keeping up to date with community interactions with our docs. For now this shows how to do so with dsctriage, but may be expanded for a more overarching "doctriage" tool in the future.

Add documentation triage overview

---

PackageMerging.md

Best practice is for commit messages and changelog messages to use the imperative mood in the present tense. See for example https://cbea.ms/git-commit/#imperative. This is what I've always done anyway, but Utkarsh points out that then it should be in our guide: https://code.launchpad.net/~racb/ubuntu/+source/ppp/+git/ppp/+merge/428546

Use the imperative mood in changelog messages

---

Setup.md

This pull request replaces `groupadd` with `adduser` in the setup instructions.
The current description implies that `groupadd` will add the user to the specified groups if the user notices that the output of `groups my_user` does not contain `lxd`, `sbuild` or `libvirt`.
Instead `groupadd` will create these groups, but does not add the user to these groups as described.

Fix missleading use of `groupadd`

---

PackageMerging.md

Nowadays, dpkg-buildpackage runs lintian by default anyway.
But either way, what is the package merging person supposed to do with the lintian output? Most of the time, lintian errors that might appear here exist in the Debian packaging already, and we don't typically add Ubuntu delta to remove lintian errors.
It is true that we don't want to *introduce* new lintian errors in an Ubuntu delta, but this is rare too, and it would simplify the instructions just to skip this step.
If someone wants to write instructions to identify only lintian errors introduced by the delta, and check for those, then feel free to do that :-)

Remove lintian from package merge instructions

---

Setup.md

The sentence was a bit misleading vs what the commands did suggest.

Setup.md change useradd into adduser

---

PackageMerging.md

I don't think this step is necessary. Does any reviewer want to stop me and tell me why this needs to be here?

Remove unnecessary "squash changelog" merge step

---

PackageFixing.md

We really spend a lot of effort in preparing and processing SRU exceptions, but it is only a little investment to be a bit extra careful on those updates.
Let us add a section mentioning how MREs are prepared in general and in there a hint about the benefit of not only wrapping the code into an update but conciously checking the release notes / changelog in regard to their match of the SRU philosophy.

Add rel-notes check to MRE preparation

---

PackageMerging.md

Code was outside code block which includes <> so some of the words became whitespace in the HTML.

PackageMerging: Update code to be in code block

---

MergeProposalReview.md

While shadowing Christian on a Patch Pilot session, I realized that he was using a different template for being used in the MP reviews.
I think that template covers more aspects of the review process, so I'm updating it here accordingly.

Adding Git section, bug reference field and updating section names related to Package Merges

---

PackageTests.md

Once people have mastered local autopkgtest they sooner or later run into different architectures and after that into armhf being even more special.
This outlines how to run an autopkgtest similar to what the real execution would look like.

Outline manunal armhf autopkgtest

---

BugFixingCheckList.md
CommittingChanges.md
README.md
Syncs.md
VersionStrings.md

We have had too many cases where referring to the security wiki page that served as the gold standard was not sufficient. Especially around going ahead via upstream merges and even more so backports and pushing new versions as MREs it needs to be spelled out to avoid common mistakes from re-occuring.
This adds explanatory text and explicit examples for:
- upstream merges going ahead of Debian
- backports of upstream versions (MRE)
- backports from -devel (same on all releases)

CommittingChanges.md: Clarify upload versioning

---

BugReportResponses.md
PackageFixing.md

Ubuntu no longer uses Freenode as discusse in
https://discourse.ubuntu.com/t/irc-move-to-libera/22472

Substitute instances of Freenode for Libera

---

Setup.md

The snapcraft deb is no longer supported and even fails to install on some systems:
https://bugs.launchpad.net/ubuntu/+source/snapcraft/+bug/2039454

Update Setup.md to replace reference to snapcraft deb

---

VersionStrings.md

version-strings: Make wording more succinct and explicit                            
Current wording states that Stable Release Updates have a different                 
scheme in the "ubuntu revision" section of the version scheme, but does             
not explicitly state that the details in this section completely override           
other guidance in other sections of the handbook regarding "ubuntu revisions".          
Previous wording leaves unclear whether an Ubuntu-specific delta released in a          
Stable Release Update should increment a) the Ubuntu delta number (ubuntuN),          
which remains part of the "ubuntu revisions" section, or b) the "increment" in          
the Stable Release Updates version string.                                          
Also make other …

version-strings: Make wording more succinct and explicit          

---

Setup.md

Since 0.77 (>=Focal) --keygen does no more exist [1] and it was only needed for very special cases. Our workflow is fine without so we do not even need to add a replacement.
[1]: https://salsa.debian.org/debian/sbuild/-/blob/main/ChangeLog.in#L83

Setup: remove outdated keygen option

---

PackageMerging.md

Adding this tool that I've found useful in debugging debian package issues.

PackageBuilding: add execsnoop-bpfcc as a tip

---

PackageMerging.md

ubuntu/devel might be a local branch and that might have gotten out of date. People could waste time until they spot to work on the wrong version.
Instead refer to the pkg remote which is the latest state of the importer and should always be a better choice for merge start/finish.

Avoid referring to a stale local branch

---

ProposedMigration.md

https://ubuntu-archive-team.ubuntu.com/sync-blacklist.txt was changed to also be https://ubuntu-archive-team.ubuntu.com/sync-blocklist.txt which allows us to change to the inclusive naming.
Fixes #111

ProposedMigration: update wording

---

PackageTests.md
ProposedMigration.md

This change was based on the comments available in the retry-autopkgtest-regressions script at https://git.launchpad.net/ubuntu-archive-tools/tree/retry-autopkgtest-regressions

Document autopkgtest cookie extraction and usage

---

PackageTests.md

The command line interface of add-apt-repository changed significantly since Ubuntu 20.10 (Groovy Gorilla).
* `-u` was removed in favor of running apt update by default and adding a `-n, --no-update` flag to opt-out instead of opt-in
* added `-P`, `--ppa` flag
See manpage for Ubuntu 20.10 (Groovy Gorilla):
https://git.launchpad.net/ubuntu/+source/software-properties/tree/debian/manpages/add-apt-repository.1?h=ubuntu/groovy-devel
See manpage for Ubuntu 20.04 LTS (Focal Fossa):
https://git.launchpad.net/ubuntu/+source/software-properties/tree/debian/manpages/add-apt-repository.1?h=ubuntu/focal-devel

PackageTests: note add-apt-repository CLI change

---

PackageMerging.md

Fixes: #131
I grepped all files for `export-orig` and this looks like it's the only place where it makes sense to mention `--for-merge`.

Show when to use --for-merge

---

MergeProposalReview.md

We've always added, updated and enqueued release note and documentation changes as needed. Let us hold each other accountable in case someone forgets about it.

release-notes/documentation reminder in the review

---

Concepts.md
DebugApportCrash.md

Concepts.MD only had reference to the one-line apt sources style, which stopped being the default in Ubuntu 24.04 Noble Numbat. Checked for other code examples showing only one-line and updated to include deb822 examples. Keeping both examples as we still support suites where one-line style is the default.

feat: Update docs to include deb822

---

VersionStrings.md

There was some confusion as to what exactly "Ubuntu changes" represents and whether devel should always start with ubuntu1 vs ubuntu0.

VersionStrings.md: clarify devel upload from upstream

---

VersionStrings.md

* fix closing `_` marker for an italic sentence
* fix link to `VersionStrings.md#version-adding-a-change-in-ubuntu-as-a-stable-release-update` by fixing the markdown syntax

Fix italic formatting and a broken link

---

MergeProposalReview.md

We haven't had a good place to raise/discuss/ensure things about changes in debian/* not being patches in d/p/*
Furthermore we only asked for upstreaming in some of those places, but the target of upstreaming differs and furthermore we lacked expressing that it is ok to mark things as Ubuntu-only if that is the right state for this delta.
This PR fixes all that in the review template to make reviews easier and more complete.

MergeProposalReview.md: changes can be in debian/*

---

PackageMerging.md

Users learning how to submit MPs through git ubuntu will often send their MPs to the server team to review due to the current git-ubuntu default reviewer value. While this default value is not revisited, let's ensure random MPs will not land in the server team queue by instructing users to explicitly add ubuntu-sponsors (or something else) as reviewers for their MPs.

Specify a reviewer for git ubuntu submit

---

CommittingChanges.md

The commit message for updating changelogs in package merges is documented as being just "changelog". Those messages are irrelevant during the merges, given the commits touching d/changelog are dropped during the merge process.
Commits touching d/changelog for a package release should be more descriptive by default to match the messages touching d/control when updating the Maintainer field.

Favor descriptive commit messages

---

VersionStrings.md

I've worked on revising the Versions page.  Mostly this is copyediting and revisions to improve clarity and readability, but I've added some more substantive changes regarding syncing, and moved up the section on no-change rebuilds.  I figure covering all the trivial situations first would get them out of the way.

Version page clarifications for development releases

---

PackageBuilding.md

Just two little fixes to errors I found whilst reading through the "Package Building" page:
1. The long name of the `-d` flag of `dpkg-buildpackage` was `--no-pre-clean` instead of `--no-check-builddeps`
2. The Markdown backticks for `sbuild` weren't closed in the "Build binary packages locally with `sbuild`" title

Small fixes for "Package Building" article

---

MergeProposalReview.md

I've found too often whole sections not applicable, making some otherwise worthwhile checks just a distracting burden to read.
=> Allow one to drop sections if all would be skips
Furthermore I've seen uncertainty like "do you need to re-review after this change". 
=> Some have naturally done that, but https://conventionalcomments.org/ provides a nice framework for it which we could utilize to make our workflow better.

Improve feedback guidance

---

ProposedMigration.md

Inspired by https://discourse.ubuntu.com/t/visualizing-and-exploring-ubuntu-excuses/59824 I was looking at the related section in our handbook and found a few things to improve around proposed migration.

Refer to excuses tools

---

TeamMigrationTriage.md
Triage.md

Along the updates of US-133 spec discussion as we rework the triage, post-standup and housekeeping this updates the relates entries in the maintainer handbook.

Triage: add migration triage

---

PackageMerging.md

git-ubuntu got default reviewer configuration in [56d1c9c470afd07](https://git.launchpad.net/git-ubuntu/commit/?id=56d1c9c470afd07bd8914337ec1f2004093fb599)
this allows setting the launchpad mp reviewer default setting for `git ubuntu submit --reviewer`) with git's config key `gitubuntu.submit.defaultReviewer`.

PackageMerging.md: mention defaultReviewer configuration through git config

---

PackageBuilding.md

I think this piece of information is quite useful for people who are not aware of the possibility.

Add information on how to get a shell into the schroot when a build fails

---

Sponsorship.md

In "Sponsorship.md", this commit and pull request changes the first mention 
of "merge proposal" to "Merge Proposal (MP)" to make it clearer that subsequent  
references to "MP" mean a "merge proposal" and also turns that first reference 
of merge proposal into a link to the "MergeProposal.md" page.

Sponsorship.md : add link to Merge Proposal (MP) page

---

PackageMerging.md

PackageMerging: Mention the usage of "--bug" in start/tag/finish commands
By using the `--bug=XXX` argument, we can prefix our tags with "lpXXX/" and avoid namespace conflicts with `old/debian`, `new/debian` etc.

PackageMerging: Mention the usage of "--bug"

---

PackageMerging.md

This addresses the latest commit that added the `--bug` flag and to makes everyone's life easier, we mention the `lpXXX/` prefix in commands.
This PR also solves PR #172

PackageMerging: Mention the needed prefix when --bug is used

---

PackageBackports.md

- make sure code blocks are render properly and the text is readable
- standardize list titles

Polish the Package Backports page
